import { expect, test, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs';
import path from 'node:path';

const app = 'http://127.0.0.1:4180';
const key = 'datapass:pilot-center:v1';
async function accessible(page: Page) {
  const violations = (await new AxeBuilder({ page }).exclude('[data-tabster-dummy]').withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations.filter((value) => ['serious', 'critical'].includes(value.impact ?? ''));
  expect(violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)).toBeLessThanOrEqual(1);
}
test.beforeEach(async ({ page }) => { await page.emulateMedia({ reducedMotion: 'reduce' }); });

test('Pilot projects share cards/table/galaxy, keyboard selection and local next actions', async ({ page }, testInfo) => {
  const monaco: string[] = [];
  page.on('request', (request) => { if (/monaco-editor|MonacoSurfaces|editor\.worker/.test(request.url())) monaco.push(request.url()); });
  await page.goto(`${app}/#/projects`);
  await page.getByRole('button', { name: 'Inspect project: Formation', exact: true }).press('Enter');
  const inspector = page.getByTestId('pilot-project-inspector');
  await expect(inspector.getByRole('heading', { name: 'Formation', exact: true })).toBeVisible();
  await inspector.getByLabel('Next action', { exact: true }).fill('Review reasoning capstone');
  await inspector.getByRole('button', { name: 'Save project notes' }).press('Enter');
  await expect(page.getByRole('status')).toContainText('Saved on this device.');
  await page.getByRole('button', { name: 'Table', exact: true }).click();
  await expect(page.getByRole('table', { name: 'Pilot projects table' })).toBeVisible();
  await accessible(page);
  await page.getByRole('button', { name: 'Galaxy', exact: true }).click();
  await expect(page.locator('[data-figure-id="figure.pilot.project-galaxy"] svg')).toBeVisible();
  await page.getByLabel('Select galaxy project').selectOption('project.d3-visual-studio');
  await expect(inspector.getByRole('heading', { name: 'D3 Visual Studio' })).toBeVisible();
  await expect(inspector.getByRole('link', { name: 'Visit website' })).toHaveAttribute('href', 'https://d3ecosite.netlify.app/sandbox/');
  await accessible(page);
  fs.mkdirSync('qa/screenshots', { recursive: true });
  await page.locator('.pilot-galaxy svg[data-conceptmotion]').scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.resolve(`qa/screenshots/v3-pilot-galaxy-${testInfo.project.name}.png`), animations: 'disabled' });
  await page.getByRole('navigation', { name: 'Pilot navigation' }).getByRole('link', { name: 'Overview' }).click();
  await expect(page.getByText('Review reasoning capstone')).toBeVisible();
  await page.reload();
  await expect(page.getByText('Review reasoning capstone')).toBeVisible();
  await accessible(page);
  expect(monaco).toEqual([]);
});

test('Pilot ideas support structured edits, filtering, undo and previewed deterministic restore', async ({ page }, testInfo) => {
  await page.goto(`${app}/#/ideas`);
  await page.getByRole('button', { name: 'New idea', exact: true }).press('Enter');
  await page.getByRole('textbox', { name: 'Idea title', exact: true }).fill('Inspect SQL grain');
  await page.getByLabel('Details', { exact: true }).fill('Explain why grouping changes the row grain.');
  await page.getByLabel('Domain', { exact: true }).selectOption('sql');
  await page.getByLabel('Status', { exact: true }).selectOption('todo');
  await page.getByLabel('Related project', { exact: true }).selectOption('project.formation');
  await page.getByLabel('Tags (comma-separated)', { exact: true }).fill('sql, reasoning');
  await page.getByRole('button', { name: 'Save idea' }).press('Enter');
  await expect(page.getByTestId('pilot-note')).toContainText('Inspect SQL grain');
  await page.getByRole('button', { name: 'Pin', exact: true }).press('Enter');
  await page.getByText('Filter ideas', { exact: true }).click();
  await page.getByLabel('Filter status').selectOption('done');
  await expect(page.getByTestId('pilot-note')).toHaveCount(0);
  await page.getByRole('button', { name: 'Clear filters' }).click();
  await page.getByLabel('Filter project').selectOption('project.code-sandbox');
  await expect(page.getByTestId('pilot-note')).toHaveCount(0);
  await page.getByLabel('Filter project').selectOption('project.formation');
  await page.getByLabel('Search ideas').fill('reasoning');
  await expect(page.getByTestId('pilot-note')).toHaveCount(1);
  await page.getByRole('button', { name: 'Clear filters' }).click();
  await page.getByRole('button', { name: 'Edit idea: Inspect SQL grain' }).click();
  await page.getByLabel('Priority', { exact: true }).selectOption('urgent');
  await page.getByRole('button', { name: 'Save idea' }).click();
  await accessible(page);
  fs.mkdirSync('qa/screenshots', { recursive: true });
  await page.getByTestId('pilot-note').scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.resolve(`qa/screenshots/v3-pilot-ideas-${testInfo.project.name}.png`), animations: 'disabled' });
  await page.reload();
  await expect(page.getByTestId('pilot-note')).toContainText('urgent');
  const before = await page.evaluate((storageKey) => localStorage.getItem(storageKey), key);
  await page.getByRole('button', { name: 'Delete idea: Inspect SQL grain' }).click();
  await expect(page.getByTestId('pilot-note')).toHaveCount(0);
  await page.getByRole('button', { name: 'Undo deletion' }).click();
  await expect(page.getByTestId('pilot-note')).toHaveCount(1);
  await page.getByRole('navigation', { name: 'Pilot navigation' }).getByRole('link', { name: 'Backups' }).click();
  const href = await page.getByRole('link', { name: 'Download private backup' }).getAttribute('href');
  expect(decodeURIComponent(href!.split(',').slice(1).join(','))).toBe(before);
  await page.getByLabel('Import JSON', { exact: true }).fill('{invalid');
  await page.getByRole('button', { name: 'Preview import' }).click();
  await expect(page.getByRole('alert')).toContainText('Invalid JSON');
  expect(await page.evaluate((storageKey) => localStorage.getItem(storageKey), key)).toBe(before);
  await page.getByLabel('Import JSON', { exact: true }).fill(before!);
  await page.getByRole('button', { name: 'Preview import' }).click();
  await expect(page.getByTestId('pilot-import-preview')).toContainText('1 ideas');
  await page.getByRole('button', { name: 'Replace local data' }).click();
  await accessible(page);
  expect(await page.evaluate((storageKey) => localStorage.getItem(storageKey), key)).toBe(before);
  await page.getByLabel('Import type').selectOption('overlay');
  await page.getByLabel('Choose a JSON file').setInputFiles({ name: 'projects.private.local.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ schemaVersion: 1, overlays: [{ projectId: 'project.formation', nextAction: 'Local overlay proof', privateRepository: 'https://example.test/local-only' }] })) });
  await page.getByRole('button', { name: 'Preview import' }).click();
  await expect(page.getByTestId('pilot-import-preview')).toContainText('Existing ideas are kept.');
  await page.getByRole('button', { name: 'Merge local overlay' }).click();
  const merged = JSON.parse((await page.evaluate((storageKey) => localStorage.getItem(storageKey), key))!);
  expect(merged.notes).toHaveLength(1);
  expect(merged.overlays[0]).toMatchObject({ projectId: 'project.formation', nextAction: 'Local overlay proof' });
  const publicHref = await page.getByRole('link', { name: 'Download public registry only' }).getAttribute('href');
  const publicExport = decodeURIComponent(publicHref!.split(',').slice(1).join(','));
  expect(publicExport).not.toContain('local-only');
  expect(publicExport).not.toContain('Local overlay proof');
  expect(publicExport).not.toContain('Inspect SQL grain');
});
