import AxeBuilder from '@axe-core/playwright';
import { expect, test, type Page } from '@playwright/test';
async function accessible(page: Page) {
  const result = await new AxeBuilder({ page }).exclude('[data-tabster-dummy]').withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  expect(result.violations.filter(issue => issue.impact === 'serious' || issue.impact === 'critical')).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
}
test.beforeEach(async ({ page }) => { await page.emulateMedia({ reducedMotion: 'reduce' }); });

test('Code Sandbox preserves corpus, URL filters, lazy editor, variants, notes and backup', async ({ page }, info) => {
  const editorRequests: string[] = [];
  page.on('request', request => { if (/(monaco-editor|MonacoSurfaces|monacoLoader|editor\.worker|json\.worker)/iu.test(request.url())) editorRequests.push(request.url()); });
  await page.goto('http://127.0.0.1:4176/');
  await expect(page.getByText('323 of 323 practice items', { exact: true })).toBeVisible();
  expect(editorRequests).toEqual([]);
  await accessible(page);
  await page.screenshot({ path: `qa/screenshots/v3-code-sandbox-catalog-${info.project.name}.png`, animations: 'disabled' });
  await page.getByRole('searchbox', { name: 'Search practice' }).fill('Filter active records');
  await expect(page).toHaveURL(/q=Filter/);
  await page.getByRole('row').filter({ hasText: 'Filter active records' }).press('Enter');
  await expect(page.getByRole('heading', { name: 'Filter active records', exact: true })).toBeVisible();
  await expect(page.locator('.monaco-editor').first()).toBeVisible();
  expect(editorRequests.length).toBeGreaterThan(0);
  await page.getByRole('textbox', { name: 'Practice code editor', exact: true }).focus();
  await page.keyboard.press('Control+A');
  await page.keyboard.insertText('SELECT 42;');
  await expect.poll(() => page.evaluate(() => window.localStorage.getItem('datapass:code-sandbox:v3'))).toContain('SELECT 42;');
  await page.getByRole('tab', { name: 'Hints', exact: true }).click();
  await page.getByRole('button', { name: 'Reveal next hint' }).click();
  await expect(page.getByText('Find the row-filter operation for the selected engine.', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Visualize', exact: true }).click();
  await expect(page.locator('[data-figure-renderer="table.transform"] svg')).toBeVisible();
  await page.getByRole('button', { name: 'Next visual step', exact: true }).click();
  await page.getByRole('tab', { name: 'Notes', exact: true }).click();
  await page.getByRole('textbox', { name: 'Your reasoning notes' }).fill('Keep row grain; filter only.');
  await page.getByRole('combobox', { name: 'Language / engine', exact: true }).selectOption('pyspark');
  await expect(page.getByText('PySpark: display, explanation and external practice only. No Spark session or Jupyter kernel.')).toBeVisible();
  await page.getByRole('tab', { name: 'Solution', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Reference explanation', exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Compare', exact: true }).click();
  await expect(page.locator('.monaco-diff-editor')).toBeVisible();
  await page.getByRole('button', { name: 'Mastered', exact: true }).click();
  await page.getByRole('button', { name: 'Flag', exact: true }).click();
  await accessible(page);
  await page.screenshot({ path: `qa/screenshots/v3-code-sandbox-${info.project.name}.png`, animations: 'disabled' });
  await page.getByRole('button', { name: 'Progress', exact: true }).click();
  await page.getByRole('button', { name: 'Export backup' }).click();
  await expect(page.getByRole('textbox', { name: 'Workspace JSON' })).toHaveValue(/Keep row grain; filter only\./);
  await page.reload();
  await page.getByRole('button', { name: 'Export backup' }).click();
  await expect(page.getByRole('textbox', { name: 'Workspace JSON' })).toHaveValue(/eng-filter-active/);
  await expect(page.getByRole('textbox', { name: 'Workspace JSON' })).toHaveValue(/SELECT 42;/);
});

test('Code Interview uses distinct sessions, submission review, flags and domain progress', async ({ page }, info) => {
  const editorRequests: string[] = [];
  page.on('request', request => { if (/(monaco-editor|MonacoSurfaces|monacoLoader)/iu.test(request.url())) editorRequests.push(request.url()); });
  await page.goto('http://127.0.0.1:4177/');
  await expect(page.getByRole('heading', { name: 'Practice the conversation, not just the answer.' })).toBeVisible();
  expect(editorRequests).toEqual([]);
  await accessible(page);
  await page.screenshot({ path: `qa/screenshots/v3-code-interview-sessions-${info.project.name}.png`, animations: 'disabled' });
  await page.getByRole('button', { name: /Quick · 12 minutes/ }).press('Enter');
  await expect(page.getByRole('timer')).toBeVisible();
  await page.getByRole('button', { name: 'Pause timer' }).click();
  await page.getByRole('radio', { name: 'Sort the whole table and keep only its first row.', exact: true }).check();
  await page.getByRole('radio', { name: 'Option B', exact: true }).check();
  await page.getByRole('radio', { name: 'Equal timestamps require a stable, documented tie-breaker.', exact: true }).check();
  await page.getByRole('button', { name: 'Flag question 1', exact: true }).click();
  await page.getByRole('button', { name: 'Submit assessment' }).click();
  await expect(page.getByText('2 / 4', { exact: true })).toBeVisible();
  await accessible(page);
  await page.screenshot({ path: `qa/screenshots/v3-code-interview-${info.project.name}.png`, animations: 'disabled' });
  await page.getByRole('button', { name: 'Progress', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Progress by domain', exact: true })).toBeVisible();
  await expect(page.getByText('2 / 4 correct · 50%', { exact: false })).toBeVisible();
  await page.getByRole('button', { name: 'Sessions', exact: true }).click();
  await page.getByRole('button', { name: /Review mistakes/ }).click();
  await expect(page.locator('[data-question-id="interview.sql.concept"]')).toBeVisible();
  await expect(page.getByRole('button', { name: /Run|Execute/ })).toHaveCount(0);
});
