import { compileTableFilter, compileTableSort, compileTableState, type TableData, type TableJoinSpec } from '@conceptmotion/core';
import { visual, practiceSource } from './model';

export const orders: TableData = { id: 'orders', columns: [{ id: 'customer' }, { id: 'amount' }], rows: [{ id: 'o1', values: { customer: 'A', amount: 100 } }, { id: 'o2', values: { customer: 'A', amount: 50 } }, { id: 'o3', values: { customer: 'B', amount: 80 } }, { id: 'o4', values: { customer: 'C', amount: 20 } }] };
const customers: TableData = { id: 'customers', columns: [{ id: 'customer' }, { id: 'segment' }], rows: [{ id: 'a', values: { customer: 'A', segment: 'Gold' } }, { id: 'b', values: { customer: 'B', segment: 'Silver' } }, { id: 'd', values: { customer: 'D', segment: 'New' } }] };
const scene = (id: string, title: string, frames: readonly ReturnType<typeof compileTableState>[]) => ({ kind: 'table', version: '3', id, title, frames });
const initial = compileTableState(orders);
const grouped: TableData = { id: 'orders', columns: [{ id: 'customer' }, { id: 'total' }], rows: ['A', 'B', 'C'].map(customer => ({ id: `group-${customer}`, values: { customer, total: orders.rows.filter(row => row.values.customer === customer).reduce((sum, row) => sum + Number(row.values.amount), 0) } })) };
export const ranked: TableData = { id: 'events', columns: [{ id: 'customer' }, { id: 'time' }, { id: 'rank' }], rows: [{ id: 'a-old', values: { customer: 'A', time: 10, rank: 2 } }, { id: 'a-new', values: { customer: 'A', time: 20, rank: 1 } }, { id: 'b-old', values: { customer: 'B', time: 15, rank: 2 } }, { id: 'b-new', values: { customer: 'B', time: 25, rank: 1 } }] };
const unranked: TableData = { ...ranked, columns: ranked.columns.filter(c => c.id !== 'rank'), rows: ranked.rows.map(row => ({ id: row.id, values: { customer: row.values.customer, time: row.values.time } })) };
const rankSort = compileTableSort(ranked, [{ columnId: 'customer' }, { columnId: 'time', direction: 'desc' }]);
const latest = compileTableFilter(ranked, { columnId: 'rank', operator: 'eq', value: 1 });
const source = practiceSource;
const joins = (['inner', 'left', 'full'] as const).map(joinType => {
  const join: TableJoinSpec = { id: `join-${joinType}`, joinType, left: orders, right: customers, leftKey: 'customer', rightKey: 'customer' };
  const counts = { inner: 3, left: 4, full: 5 };
  const text = { inner: 'Only matching pairs survive: three orders for A and B.', left: 'Every order survives; customer C receives NULL dimension columns.', full: 'Both sides survive: customer C and customer D produce unmatched rows.' };
  return visual(`sql-${joinType}-join`, `${joinType[0].toUpperCase()}${joinType.slice(1)} join`, 'SQL', 'table.join', { kind: 'join', version: '3', id: `sql-${joinType}-join`, join, revealCounts: [0, 2, counts[joinType]] }, ['Read keys, not row positions.', 'A has two orders: each pairs with the same customer row.', text[joinType]], `Join cardinality: ${counts[joinType]} output rows; source IDs identify each pair.`, `${joinType}-join`, joinType === 'inner' ? ['al-hash-join', 'eng-inner-join'] : [], source);
});
const history: TableData = { id: 'customer-history', columns: ['customer', 'value', 'from', 'to', 'current'].map(id => ({ id })), rows: [{ id: 'A-v1', values: { customer: 'A', value: 80, from: 1, to: null, current: true } }] };
const changed: TableData = { ...history, rows: [{ id: 'A-v1', values: { customer: 'A', value: 80, from: 1, to: 2, current: false } }, { id: 'A-v2', values: { customer: 'A', value: 100, from: 2, to: null, current: true } }] };
const grainJoin: TableJoinSpec = { id: 'grain-multiplication', joinType: 'inner', left: orders, right: { ...customers, rows: [...customers.rows, { id: 'a2', values: { customer: 'A', segment: 'Historic' } }] }, leftKey: 'customer', rightKey: 'customer' };

export const sqlVisuals = [
  visual('sql-filter', 'Filter without changing the grain', 'SQL', 'table.transform', scene('sql-filter', 'WHERE amount >= 70', [initial, compileTableFilter(orders, { columnId: 'amount', operator: 'gte', value: 70 })]), ['Four orders enter the predicate.', 'Only o1 and o3 satisfy amount >= 70; their identities are unchanged.'], 'Filtering removes rows, not columns, and keeps surviving row IDs.', 'filter', ['eng-filter-active'], source),
  ...joins,
  visual('sql-group', 'Group changes the grain', 'SQL', 'table.transform', scene('sql-group', 'Orders → customer totals', [initial, compileTableState(grouped)]), ['Each row is one order: A appears twice.', 'Collapse by customer: A=150, B=80, C=20. Each output row is now one customer.'], 'The total remains 250 while four order rows become three customer rows.', 'groupby', ['eng-group-sum'], source),
  visual('sql-window-rank', 'Window rank preserves the rows', 'SQL', 'table.transform', scene('sql-window-rank', 'Partition by customer; newest first', [compileTableState(unranked), rankSort]), ['Start with four events, including two per customer.', 'ROW_NUMBER is 1 for each newest event and 2 for the older event. No row is aggregated away.'], 'Window functions add an answer to each input row; grain stays event.', 'sql-ranking', [], source),
  visual('sql-latest-row', 'Latest row: rank, then retain', 'SQL', 'table.transform', scene('sql-latest-row', 'Deterministic latest event per key', [compileTableState(unranked), rankSort, latest]), ['Define the business key and event order.', 'Rank separately inside A and B; a stable tie-breaker is required if times tie.', 'Keep a-new and b-new. Both are original event IDs.'], 'Latest-row dedupe retains one whole original record per business key.', 'latest-row', ['eng-latest-row'], source),
  visual('sql-qualify', 'QUALIFY filters a window result', 'SQL', 'table.transform', scene('sql-qualify', 'Window evaluation → QUALIFY rank = 1', [compileTableState(unranked), rankSort, latest]), ['WHERE would run before the rank exists.', 'The window result attaches rank to every event.', 'QUALIFY keeps rank=1 after window evaluation; equivalent nested-query semantics work elsewhere.'], 'Window calculation precedes QUALIFY; dialect support is not universal.', 'qualify', [], source),
  visual('sql-grain', 'A join can multiply the grain', 'SQL', 'table.join', { kind: 'join', version: '3', id: 'sql-grain', join: grainJoin, revealCounts: [0, 4, 5] }, ['The dimension contains two A records, so customer is not unique.', 'Two A orders × two A dimension versions produce four pairs.', 'B contributes one more pair. Five rows are not five distinct orders.'], 'Joining on a non-unique key creates multiplicity; check grain before summing.', 'grain-cardinality', [], source),
  visual('sql-cdc', 'SCD2 preserves old and new states', 'SQL', 'table.transform', scene('sql-cdc', 'Close one validity interval; append another', [compileTableState(history), compileTableState(changed)]), ['A-v1 is current from time 1 with value 80.', 'At time 2, close A-v1 and append A-v2=100; the old row is retained.'], 'Exactly one version is current; validity intervals are adjacent and non-overlapping.', 'cdc-scd2', [], source),
];
