import { compileTableFilter, compileTableState, type DiagramSpec, type LoopSceneSpec, type TableData, type WorkflowSpec } from '@conceptmotion/core';
import { visual, mlSource } from './model';

const graph = (id: string, labels: readonly string[], links: readonly [number, number][], frames: readonly { activeNodeIds?: readonly string[]; activeEdgeIds?: readonly string[]; failedNodeIds?: readonly string[] }[]) => ({ kind: 'diagram' as const, version: '3', id, title: labels.join(' → '), layout: { provider: 'layered' as const }, nodes: labels.map((label, i) => ({ id: `n${i}`, label })), edges: links.map(([from, to], i) => ({ id: `e${i}`, from: { nodeId: `n${from}` }, to: { nodeId: `n${to}` }, flowKind: 'data' as const })), frames: frames.map((f, i) => ({ ...f, id: `step-${i}` })) });
const pathFrames = (count: number) => Array.from({ length: count }, (_, i) => ({ activeNodeIds: [`n${i}`], activeEdgeIds: i ? [`e${i - 1}`] : [] }));
const batchSpec: LoopSceneSpec = { kind: 'loop', version: '3', id: 'de-batching', title: 'Bounded batches, including the tail', items: Array.from({ length: 7 }, (_, i) => ({ id: `i${i}`, value: i + 1 })), codeLines: [{ id: 'batch', text: 'items[start:start + batch_size]' }], frames: [0, 3, 6].map((start, index) => ({ id: `batch-${index}`, iteration: index, activeItemIds: Array.from({ length: Math.min(3, 7 - start) }, (_, n) => `i${start + n}`), doneItemIds: Array.from({ length: start }, (_, n) => `i${n}`), codeLineIds: ['batch'], variables: { size: Math.min(3, 7 - start), processed: start }, operation: 'bounded slice', caption: index === 2 ? 'The final batch contains only item 7; do not drop the partial tail.' : `Process items ${start + 1}–${start + 3}, at most three at a time.` })) };
const partitions: TableData = { id: 'partitions', columns: [{ id: 'date' }, { id: 'rows' }], rows: [{ id: 'p1', values: { date: '2026-09-01', rows: 100 } }, { id: 'p2', values: { date: '2026-09-02', rows: 200 } }, { id: 'p3', values: { date: '2026-09-03', rows: 150 } }] };
export const retryWorkflow: WorkflowSpec = { kind: 'workflow', version: '3', id: 'de-retry', title: 'Retry a keyed write safely', preset: 'generic', nodes: [{ id: 'extract', label: 'Extract' }, { id: 'upsert', label: 'Upsert by event ID' }, { id: 'publish', label: 'Publish' }], edges: [{ id: 'e1', from: 'extract', to: 'upsert', condition: 'success' }, { id: 'e2', from: 'upsert', to: 'publish', condition: 'success' }], runs: [{ id: 'fixture-run', frames: [{ id: 'ready', states: { extract: { status: 'running' } } }, { id: 'write', states: { extract: { status: 'success' }, upsert: { status: 'running', attempt: 1 } } }, { id: 'retry', states: { upsert: { status: 'retrying', attempt: 2 } } }, { id: 'commit', states: { upsert: { status: 'success', attempt: 2 }, publish: { status: 'running' } } }, { id: 'complete', states: { publish: { status: 'success' } } }] }] };
const topo: DiagramSpec & { frames: readonly unknown[] } = graph('algorithm-topological', ['Extract', 'Clean', 'Validate', 'Publish'], [[0, 1], [0, 2], [1, 3], [2, 3]], [{ activeNodeIds: ['n0'] }, { activeNodeIds: ['n1', 'n2'], activeEdgeIds: ['e0', 'e1'] }, { activeNodeIds: ['n2'] }, { activeNodeIds: ['n3'], activeEdgeIds: ['e2', 'e3'] }]);
export const systemsVisuals = [
  visual('algorithm-bfs', 'BFS explores one frontier at a time', 'Algorithms', 'diagram.flow', graph('algorithm-bfs', ['A', 'B', 'C', 'D', 'E'], [[0, 1], [0, 2], [1, 3], [2, 4]], [{ activeNodeIds: ['n0'] }, { activeNodeIds: ['n1', 'n2'], activeEdgeIds: ['e0', 'e1'] }, { activeNodeIds: ['n3', 'n4'], activeEdgeIds: ['e2', 'e3'] }]), ['Start at A, distance 0.', 'FIFO discovery reaches B and C, both distance 1.', 'D and E are distance 2. A visited set prevents rediscovery.'], 'BFS discovers nodes in nondecreasing shortest-path distance on an unweighted graph.', 'bfs', ['al-graph-traversal']),
  visual('algorithm-topological', 'Topological order waits for every prerequisite', 'Algorithms', 'diagram.flow', topo, ['Extract has no incoming dependencies.', 'Extract releases Clean and Validate; these may run independently.', 'Even after Clean finishes, Publish still waits for Validate.', 'Only after both predecessors complete can Publish be released.'], 'A node becomes ready only when its remaining indegree reaches zero.', 'topological-order', ['al-topological-sort']),
  visual('de-batching', 'Batching keeps working memory bounded', 'Data engineering', 'algorithm.loop', batchSpec, batchSpec.frames.map(f => String(f.caption)), 'Batches partition all seven inputs exactly once; size never exceeds three.', 'batch', ['al-batching']),
  visual('de-partition-pruning', 'Partition pruning avoids irrelevant blocks', 'Data engineering', 'table.transform', { kind: 'table', version: '3', id: 'de-partition-pruning', title: 'Choose partitions before scanning their rows', frames: [compileTableState(partitions), compileTableFilter(partitions, { columnId: 'date', operator: 'eq', value: '2026-09-02' })] }, ['All three partitions are candidates: 450 rows in total.', 'A date predicate selects only p2: scan 200 rows instead of 450. Partition metadata, not every data row, makes this decision.'], 'Pruning changes work read, not the logical answer of the query.', 'partition'),
  visual('de-medallion', 'Bronze → Silver → Gold adds trust', 'Data engineering', 'diagram.flow', graph('de-medallion', ['Bronze / raw', 'Silver / valid', 'Gold / business'], [[0, 1], [1, 2]], pathFrames(3)), ['Bronze retains replayable source-aligned data.', 'Silver applies types, keys, deduplication and quality checks.', 'Gold expresses a business grain and metric definitions.'], 'Each layer has a contract; Gold is not merely another copy of raw data.', 'medallion'),
  visual('de-retry', 'Retry and idempotency are separate', 'Data engineering', 'workflow.run', retryWorkflow, ['Extract is running; downstream tasks wait.', 'Extraction succeeds; a keyed write begins.', 'A response is lost. Retry uses the same event ID and write key.', 'The repeated upsert has the same state effect; publish is now eligible.', 'All tasks succeed. This is a prerecorded explanation, not execution.'], 'Idempotency means apply(apply(state,event),event) = apply(state,event); retry alone does not guarantee it.', 'retry-idempotency'),
  visual('de-pure-transform', 'A pure transform has explicit input and output', 'Data engineering', 'diagram.flow', graph('de-pure-transform', ['Input rows', 'Validate types', 'Transform', 'Output rows'], [[0, 1], [1, 2], [2, 3]], pathFrames(4)), ['Input is a value, not a hidden network connection.', 'Validation makes accepted and rejected shapes explicit.', 'The transform depends only on input and declared parameters.', 'The same input produces the same output; persistence is a separate boundary.'], 'Pure transformation is deterministic and has no hidden I/O or mutation of its input.', 'pure-transform'),
  visual('ml-regression', 'Regression reduces residual error', 'ML / statistics', 'statistics.regression', { kind: 'regression', version: '3', id: 'ml-regression', title: 'Fit a line to three observations', points: [{ id: 'p1', x: 1, y: 2 }, { id: 'p2', x: 2, y: 4 }, { id: 'p3', x: 3, y: 6 }], frames: [{ id: 'initial', slope: 0, intercept: 0, operation: 'baseline', caption: 'A zero prediction leaves large residuals.' }, { id: 'improve', slope: 1, intercept: 0, operation: 'reduce error', caption: 'Slope 1 moves predictions toward each observation.' }, { id: 'fit', slope: 2, intercept: 0, operation: 'exact fixture fit', caption: 'Slope 2 fits this illustrative dataset exactly; this does not prove generalization.' }] }, ['Initial MSE=56/3.', 'At slope 1, MSE=14/3.', 'At slope 2, MSE=0 for this exact fixture. Holdout evaluation remains separate.'], 'Residual = observed minus predicted; MSE averages squared residuals.', 'linear', [], mlSource),
  visual('ml-decision-tree', 'A decision follows one tree path', 'ML / statistics', 'diagram.flow', graph('ml-decision-tree', ['age < 30?', 'income < 50?', 'Class B', 'Class A', 'Class C'], [[0, 1], [0, 2], [1, 3], [1, 4]], [{ activeNodeIds: ['n0'] }, { activeNodeIds: ['n1'], activeEdgeIds: ['e0'] }, { activeNodeIds: ['n3'], activeEdgeIds: ['e0', 'e2'] }]), ['For age=25, take the true branch at age < 30.', 'For income=40, take the true branch at income < 50.', 'Reach Class A. Only one path contributes to this single-tree prediction.'], 'A tree partitions feature space through explicit tests; a deep tree can overfit.', 'tree', [], mlSource),
  visual('ml-leakage', 'Split before fitting preprocessing', 'ML / statistics', 'diagram.flow', graph('ml-leakage', ['Dataset', 'Train split', 'Test split', 'Fit scaler / model', 'Evaluate'], [[0, 1], [0, 2], [1, 3], [3, 4], [2, 4], [2, 3]], [{ activeNodeIds: ['n2', 'n3'], activeEdgeIds: ['e5'], failedNodeIds: ['n3'] }, { activeNodeIds: ['n1', 'n3'], activeEdgeIds: ['e2'] }, { activeNodeIds: ['n2', 'n4'], activeEdgeIds: ['e3', 'e4'] }]), ['Leaky path: fitting preprocessing with test information contaminates training. The highlighted test→fit edge is forbidden.', 'Correct path: fit preprocessing and the model on training data only.', 'Apply fitted transforms to test data and evaluate without refitting.'], 'Evaluation data must not influence fitted preprocessing, feature selection or model parameters.', 'validation-leakage', [], mlSource),
];
